// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	CountUsers(ctx context.Context) (int64, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetDefaultRole(ctx context.Context) (Role, error)
	GetPermissionByName(ctx context.Context, name string) (Permission, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
