dir: "mocks"
filename: "mock_{{.InterfaceName}}.go"
pkgname: "mocks"
structname: "Mock{{.InterfaceName}}"
packages:
  go-web-template/internal/domains/user:
    interfaces:
      UserServiceInterface:
  go-web-template/internal/domains/auth:
    interfaces:
      AuthServiceInterface:
  go-web-template/internal/middleware:
    interfaces:
      AuthMiddlewareInterface:
  go-web-template/internal/mailer:
    interfaces:
      MailerInterface:
  go-web-template/internal/tokens:
    interfaces:
      TokenStoreInterface:
