services:
  prometheus:
    volumes:
      - ./config/docker/prometheus/prometheus.local.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"

  loki:
    ports:
      - "3100:3100"

  grafana:
    ports:
      - "3000:3000"
