// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-web-template/internal/domains/user"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthServiceInterface creates a new instance of MockAuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type MockAuthServiceInterface struct {
	mock.Mock
}

type MockAuthServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterface_Expecter {
	return &MockAuthServiceInterface_Expecter{mock: &_m.Mock}
}

// ConfirmEmail provides a mock function for the type MockAuthServiceInterface
func (_mock *MockAuthServiceInterface) ConfirmEmail(ctx context.Context, tokenID string) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthServiceInterface_ConfirmEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmEmail'
type MockAuthServiceInterface_ConfirmEmail_Call struct {
	*mock.Call
}

// ConfirmEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockAuthServiceInterface_Expecter) ConfirmEmail(ctx interface{}, tokenID interface{}) *MockAuthServiceInterface_ConfirmEmail_Call {
	return &MockAuthServiceInterface_ConfirmEmail_Call{Call: _e.mock.On("ConfirmEmail", ctx, tokenID)}
}

func (_c *MockAuthServiceInterface_ConfirmEmail_Call) Run(run func(ctx context.Context, tokenID string)) *MockAuthServiceInterface_ConfirmEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthServiceInterface_ConfirmEmail_Call) Return(err error) *MockAuthServiceInterface_ConfirmEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthServiceInterface_ConfirmEmail_Call) RunAndReturn(run func(ctx context.Context, tokenID string) error) *MockAuthServiceInterface_ConfirmEmail_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockAuthServiceInterface
func (_mock *MockAuthServiceInterface) CreateUser(ctx context.Context, displayName string, email string, password string) (*user.User, error) {
	ret := _mock.Called(ctx, displayName, email, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*user.User, error)); ok {
		return returnFunc(ctx, displayName, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *user.User); ok {
		r0 = returnFunc(ctx, displayName, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, displayName, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceInterface_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthServiceInterface_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - displayName string
//   - email string
//   - password string
func (_e *MockAuthServiceInterface_Expecter) CreateUser(ctx interface{}, displayName interface{}, email interface{}, password interface{}) *MockAuthServiceInterface_CreateUser_Call {
	return &MockAuthServiceInterface_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, displayName, email, password)}
}

func (_c *MockAuthServiceInterface_CreateUser_Call) Run(run func(ctx context.Context, displayName string, email string, password string)) *MockAuthServiceInterface_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthServiceInterface_CreateUser_Call) Return(user1 *user.User, err error) *MockAuthServiceInterface_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockAuthServiceInterface_CreateUser_Call) RunAndReturn(run func(ctx context.Context, displayName string, email string, password string) (*user.User, error)) *MockAuthServiceInterface_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockAuthServiceInterface
func (_mock *MockAuthServiceInterface) GetUserByID(ctx context.Context, userID int64) (*user.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*user.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *user.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceInterface_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockAuthServiceInterface_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAuthServiceInterface_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockAuthServiceInterface_GetUserByID_Call {
	return &MockAuthServiceInterface_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockAuthServiceInterface_GetUserByID_Call) Run(run func(ctx context.Context, userID int64)) *MockAuthServiceInterface_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthServiceInterface_GetUserByID_Call) Return(user1 *user.User, err error) *MockAuthServiceInterface_GetUserByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockAuthServiceInterface_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID int64) (*user.User, error)) *MockAuthServiceInterface_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthServiceInterface
func (_mock *MockAuthServiceInterface) Register(ctx context.Context, displayName string, email string, password string) error {
	ret := _mock.Called(ctx, displayName, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, displayName, email, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthServiceInterface_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthServiceInterface_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - displayName string
//   - email string
//   - password string
func (_e *MockAuthServiceInterface_Expecter) Register(ctx interface{}, displayName interface{}, email interface{}, password interface{}) *MockAuthServiceInterface_Register_Call {
	return &MockAuthServiceInterface_Register_Call{Call: _e.mock.On("Register", ctx, displayName, email, password)}
}

func (_c *MockAuthServiceInterface_Register_Call) Run(run func(ctx context.Context, displayName string, email string, password string)) *MockAuthServiceInterface_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthServiceInterface_Register_Call) Return(err error) *MockAuthServiceInterface_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthServiceInterface_Register_Call) RunAndReturn(run func(ctx context.Context, displayName string, email string, password string) error) *MockAuthServiceInterface_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RequestPasswordReset provides a mock function for the type MockAuthServiceInterface
func (_mock *MockAuthServiceInterface) RequestPasswordReset(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthServiceInterface_RequestPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPasswordReset'
type MockAuthServiceInterface_RequestPasswordReset_Call struct {
	*mock.Call
}

// RequestPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthServiceInterface_Expecter) RequestPasswordReset(ctx interface{}, email interface{}) *MockAuthServiceInterface_RequestPasswordReset_Call {
	return &MockAuthServiceInterface_RequestPasswordReset_Call{Call: _e.mock.On("RequestPasswordReset", ctx, email)}
}

func (_c *MockAuthServiceInterface_RequestPasswordReset_Call) Run(run func(ctx context.Context, email string)) *MockAuthServiceInterface_RequestPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthServiceInterface_RequestPasswordReset_Call) Return(err error) *MockAuthServiceInterface_RequestPasswordReset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthServiceInterface_RequestPasswordReset_Call) RunAndReturn(run func(ctx context.Context, email string) error) *MockAuthServiceInterface_RequestPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// ResendConfirmation provides a mock function for the type MockAuthServiceInterface
func (_mock *MockAuthServiceInterface) ResendConfirmation(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ResendConfirmation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthServiceInterface_ResendConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendConfirmation'
type MockAuthServiceInterface_ResendConfirmation_Call struct {
	*mock.Call
}

// ResendConfirmation is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthServiceInterface_Expecter) ResendConfirmation(ctx interface{}, email interface{}) *MockAuthServiceInterface_ResendConfirmation_Call {
	return &MockAuthServiceInterface_ResendConfirmation_Call{Call: _e.mock.On("ResendConfirmation", ctx, email)}
}

func (_c *MockAuthServiceInterface_ResendConfirmation_Call) Run(run func(ctx context.Context, email string)) *MockAuthServiceInterface_ResendConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthServiceInterface_ResendConfirmation_Call) Return(err error) *MockAuthServiceInterface_ResendConfirmation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthServiceInterface_ResendConfirmation_Call) RunAndReturn(run func(ctx context.Context, email string) error) *MockAuthServiceInterface_ResendConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function for the type MockAuthServiceInterface
func (_mock *MockAuthServiceInterface) ResetPassword(ctx context.Context, tokenID string, password string, confirmation string) (int64, error) {
	ret := _mock.Called(ctx, tokenID, password, confirmation)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (int64, error)); ok {
		return returnFunc(ctx, tokenID, password, confirmation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) int64); ok {
		r0 = returnFunc(ctx, tokenID, password, confirmation)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, tokenID, password, confirmation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceInterface_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockAuthServiceInterface_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
//   - password string
//   - confirmation string
func (_e *MockAuthServiceInterface_Expecter) ResetPassword(ctx interface{}, tokenID interface{}, password interface{}, confirmation interface{}) *MockAuthServiceInterface_ResetPassword_Call {
	return &MockAuthServiceInterface_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, tokenID, password, confirmation)}
}

func (_c *MockAuthServiceInterface_ResetPassword_Call) Run(run func(ctx context.Context, tokenID string, password string, confirmation string)) *MockAuthServiceInterface_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthServiceInterface_ResetPassword_Call) Return(n int64, err error) *MockAuthServiceInterface_ResetPassword_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAuthServiceInterface_ResetPassword_Call) RunAndReturn(run func(ctx context.Context, tokenID string, password string, confirmation string) (int64, error)) *MockAuthServiceInterface_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCredentials provides a mock function for the type MockAuthServiceInterface
func (_mock *MockAuthServiceInterface) ValidateCredentials(ctx context.Context, email string, password string) (*user.User, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCredentials")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*user.User, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *user.User); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceInterface_ValidateCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCredentials'
type MockAuthServiceInterface_ValidateCredentials_Call struct {
	*mock.Call
}

// ValidateCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuthServiceInterface_Expecter) ValidateCredentials(ctx interface{}, email interface{}, password interface{}) *MockAuthServiceInterface_ValidateCredentials_Call {
	return &MockAuthServiceInterface_ValidateCredentials_Call{Call: _e.mock.On("ValidateCredentials", ctx, email, password)}
}

func (_c *MockAuthServiceInterface_ValidateCredentials_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuthServiceInterface_ValidateCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthServiceInterface_ValidateCredentials_Call) Return(user1 *user.User, err error) *MockAuthServiceInterface_ValidateCredentials_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockAuthServiceInterface_ValidateCredentials_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*user.User, error)) *MockAuthServiceInterface_ValidateCredentials_Call {
	_c.Call.Return(run)
	return _c
}
