// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-web-template/internal/domains/user"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserServiceInterface creates a new instance of MockUserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type MockUserServiceInterface struct {
	mock.Mock
}

type MockUserServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceInterface) EXPECT() *MockUserServiceInterface_Expecter {
	return &MockUserServiceInterface_Expecter{mock: &_m.Mock}
}

// ListUsers provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) ListUsers(ctx context.Context, page int, pageSize int) (*user.PaginatedUsers, error) {
	ret := _mock.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *user.PaginatedUsers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*user.PaginatedUsers, error)); ok {
		return returnFunc(ctx, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *user.PaginatedUsers); ok {
		r0 = returnFunc(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.PaginatedUsers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserServiceInterface_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserServiceInterface_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
func (_e *MockUserServiceInterface_Expecter) ListUsers(ctx interface{}, page interface{}, pageSize interface{}) *MockUserServiceInterface_ListUsers_Call {
	return &MockUserServiceInterface_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, page, pageSize)}
}

func (_c *MockUserServiceInterface_ListUsers_Call) Run(run func(ctx context.Context, page int, pageSize int)) *MockUserServiceInterface_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_ListUsers_Call) Return(paginatedUsers *user.PaginatedUsers, err error) *MockUserServiceInterface_ListUsers_Call {
	_c.Call.Return(paginatedUsers, err)
	return _c
}

func (_c *MockUserServiceInterface_ListUsers_Call) RunAndReturn(run func(ctx context.Context, page int, pageSize int) (*user.PaginatedUsers, error)) *MockUserServiceInterface_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}
