// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthMiddlewareInterface creates a new instance of MockAuthMiddlewareInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthMiddlewareInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthMiddlewareInterface {
	mock := &MockAuthMiddlewareInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthMiddlewareInterface is an autogenerated mock type for the AuthMiddlewareInterface type
type MockAuthMiddlewareInterface struct {
	mock.Mock
}

type MockAuthMiddlewareInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthMiddlewareInterface) EXPECT() *MockAuthMiddlewareInterface_Expecter {
	return &MockAuthMiddlewareInterface_Expecter{mock: &_m.Mock}
}

// ClearSessionCookie provides a mock function for the type MockAuthMiddlewareInterface
func (_mock *MockAuthMiddlewareInterface) ClearSessionCookie(w http.ResponseWriter) {
	_mock.Called(w)
	return
}

// MockAuthMiddlewareInterface_ClearSessionCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSessionCookie'
type MockAuthMiddlewareInterface_ClearSessionCookie_Call struct {
	*mock.Call
}

// ClearSessionCookie is a helper method to define mock.On call
//   - w http.ResponseWriter
func (_e *MockAuthMiddlewareInterface_Expecter) ClearSessionCookie(w interface{}) *MockAuthMiddlewareInterface_ClearSessionCookie_Call {
	return &MockAuthMiddlewareInterface_ClearSessionCookie_Call{Call: _e.mock.On("ClearSessionCookie", w)}
}

func (_c *MockAuthMiddlewareInterface_ClearSessionCookie_Call) Run(run func(w http.ResponseWriter)) *MockAuthMiddlewareInterface_ClearSessionCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthMiddlewareInterface_ClearSessionCookie_Call) Return() *MockAuthMiddlewareInterface_ClearSessionCookie_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthMiddlewareInterface_ClearSessionCookie_Call) RunAndReturn(run func(w http.ResponseWriter)) *MockAuthMiddlewareInterface_ClearSessionCookie_Call {
	_c.Run(run)
	return _c
}

// CreateLoginSession provides a mock function for the type MockAuthMiddlewareInterface
func (_mock *MockAuthMiddlewareInterface) CreateLoginSession(ctx context.Context, userID int64, rememberMe bool) (string, int, error) {
	ret := _mock.Called(ctx, userID, rememberMe)

	if len(ret) == 0 {
		panic("no return value specified for CreateLoginSession")
	}

	var r0 string
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) (string, int, error)); ok {
		return returnFunc(ctx, userID, rememberMe)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) string); ok {
		r0 = returnFunc(ctx, userID, rememberMe)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, bool) int); ok {
		r1 = returnFunc(ctx, userID, rememberMe)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, bool) error); ok {
		r2 = returnFunc(ctx, userID, rememberMe)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthMiddlewareInterface_CreateLoginSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLoginSession'
type MockAuthMiddlewareInterface_CreateLoginSession_Call struct {
	*mock.Call
}

// CreateLoginSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - rememberMe bool
func (_e *MockAuthMiddlewareInterface_Expecter) CreateLoginSession(ctx interface{}, userID interface{}, rememberMe interface{}) *MockAuthMiddlewareInterface_CreateLoginSession_Call {
	return &MockAuthMiddlewareInterface_CreateLoginSession_Call{Call: _e.mock.On("CreateLoginSession", ctx, userID, rememberMe)}
}

func (_c *MockAuthMiddlewareInterface_CreateLoginSession_Call) Run(run func(ctx context.Context, userID int64, rememberMe bool)) *MockAuthMiddlewareInterface_CreateLoginSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthMiddlewareInterface_CreateLoginSession_Call) Return(id string, maxAge int, err error) *MockAuthMiddlewareInterface_CreateLoginSession_Call {
	_c.Call.Return(id, maxAge, err)
	return _c
}

func (_c *MockAuthMiddlewareInterface_CreateLoginSession_Call) RunAndReturn(run func(ctx context.Context, userID int64, rememberMe bool) (string, int, error)) *MockAuthMiddlewareInterface_CreateLoginSession_Call {
	_c.Call.Return(run)
	return _c
}

// DestroySession provides a mock function for the type MockAuthMiddlewareInterface
func (_mock *MockAuthMiddlewareInterface) DestroySession(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DestroySession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthMiddlewareInterface_DestroySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DestroySession'
type MockAuthMiddlewareInterface_DestroySession_Call struct {
	*mock.Call
}

// DestroySession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockAuthMiddlewareInterface_Expecter) DestroySession(ctx interface{}, sessionID interface{}) *MockAuthMiddlewareInterface_DestroySession_Call {
	return &MockAuthMiddlewareInterface_DestroySession_Call{Call: _e.mock.On("DestroySession", ctx, sessionID)}
}

func (_c *MockAuthMiddlewareInterface_DestroySession_Call) Run(run func(ctx context.Context, sessionID string)) *MockAuthMiddlewareInterface_DestroySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthMiddlewareInterface_DestroySession_Call) Return(err error) *MockAuthMiddlewareInterface_DestroySession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthMiddlewareInterface_DestroySession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockAuthMiddlewareInterface_DestroySession_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllSessions provides a mock function for the type MockAuthMiddlewareInterface
func (_mock *MockAuthMiddlewareInterface) RevokeAllSessions(ctx context.Context, userID int64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthMiddlewareInterface_RevokeAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllSessions'
type MockAuthMiddlewareInterface_RevokeAllSessions_Call struct {
	*mock.Call
}

// RevokeAllSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAuthMiddlewareInterface_Expecter) RevokeAllSessions(ctx interface{}, userID interface{}) *MockAuthMiddlewareInterface_RevokeAllSessions_Call {
	return &MockAuthMiddlewareInterface_RevokeAllSessions_Call{Call: _e.mock.On("RevokeAllSessions", ctx, userID)}
}

func (_c *MockAuthMiddlewareInterface_RevokeAllSessions_Call) Run(run func(ctx context.Context, userID int64)) *MockAuthMiddlewareInterface_RevokeAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthMiddlewareInterface_RevokeAllSessions_Call) Return(err error) *MockAuthMiddlewareInterface_RevokeAllSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthMiddlewareInterface_RevokeAllSessions_Call) RunAndReturn(run func(ctx context.Context, userID int64) error) *MockAuthMiddlewareInterface_RevokeAllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// SetSessionCookie provides a mock function for the type MockAuthMiddlewareInterface
func (_mock *MockAuthMiddlewareInterface) SetSessionCookie(w http.ResponseWriter, id string, maxAge int) {
	_mock.Called(w, id, maxAge)
	return
}

// MockAuthMiddlewareInterface_SetSessionCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSessionCookie'
type MockAuthMiddlewareInterface_SetSessionCookie_Call struct {
	*mock.Call
}

// SetSessionCookie is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - id string
//   - maxAge int
func (_e *MockAuthMiddlewareInterface_Expecter) SetSessionCookie(w interface{}, id interface{}, maxAge interface{}) *MockAuthMiddlewareInterface_SetSessionCookie_Call {
	return &MockAuthMiddlewareInterface_SetSessionCookie_Call{Call: _e.mock.On("SetSessionCookie", w, id, maxAge)}
}

func (_c *MockAuthMiddlewareInterface_SetSessionCookie_Call) Run(run func(w http.ResponseWriter, id string, maxAge int)) *MockAuthMiddlewareInterface_SetSessionCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthMiddlewareInterface_SetSessionCookie_Call) Return() *MockAuthMiddlewareInterface_SetSessionCookie_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthMiddlewareInterface_SetSessionCookie_Call) RunAndReturn(run func(w http.ResponseWriter, id string, maxAge int)) *MockAuthMiddlewareInterface_SetSessionCookie_Call {
	_c.Run(run)
	return _c
}

// WebClientAuthentication provides a mock function for the type MockAuthMiddlewareInterface
func (_mock *MockAuthMiddlewareInterface) WebClientAuthentication(next http.Handler) http.Handler {
	ret := _mock.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for WebClientAuthentication")
	}

	var r0 http.Handler
	if returnFunc, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = returnFunc(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	return r0
}

// MockAuthMiddlewareInterface_WebClientAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WebClientAuthentication'
type MockAuthMiddlewareInterface_WebClientAuthentication_Call struct {
	*mock.Call
}

// WebClientAuthentication is a helper method to define mock.On call
//   - next http.Handler
func (_e *MockAuthMiddlewareInterface_Expecter) WebClientAuthentication(next interface{}) *MockAuthMiddlewareInterface_WebClientAuthentication_Call {
	return &MockAuthMiddlewareInterface_WebClientAuthentication_Call{Call: _e.mock.On("WebClientAuthentication", next)}
}

func (_c *MockAuthMiddlewareInterface_WebClientAuthentication_Call) Run(run func(next http.Handler)) *MockAuthMiddlewareInterface_WebClientAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.Handler
		if args[0] != nil {
			arg0 = args[0].(http.Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthMiddlewareInterface_WebClientAuthentication_Call) Return(handler http.Handler) *MockAuthMiddlewareInterface_WebClientAuthentication_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *MockAuthMiddlewareInterface_WebClientAuthentication_Call) RunAndReturn(run func(next http.Handler) http.Handler) *MockAuthMiddlewareInterface_WebClientAuthentication_Call {
	_c.Call.Return(run)
	return _c
}
