// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenStoreInterface creates a new instance of MockTokenStoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenStoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenStoreInterface {
	mock := &MockTokenStoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenStoreInterface is an autogenerated mock type for the TokenStoreInterface type
type MockTokenStoreInterface struct {
	mock.Mock
}

type MockTokenStoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenStoreInterface) EXPECT() *MockTokenStoreInterface_Expecter {
	return &MockTokenStoreInterface_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type MockTokenStoreInterface
func (_mock *MockTokenStoreInterface) Consume(ctx context.Context, purpose string, id string) (int64, error) {
	ret := _mock.Called(ctx, purpose, id)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, purpose, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, purpose, id)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, purpose, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenStoreInterface_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockTokenStoreInterface_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - purpose string
//   - id string
func (_e *MockTokenStoreInterface_Expecter) Consume(ctx interface{}, purpose interface{}, id interface{}) *MockTokenStoreInterface_Consume_Call {
	return &MockTokenStoreInterface_Consume_Call{Call: _e.mock.On("Consume", ctx, purpose, id)}
}

func (_c *MockTokenStoreInterface_Consume_Call) Run(run func(ctx context.Context, purpose string, id string)) *MockTokenStoreInterface_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenStoreInterface_Consume_Call) Return(n int64, err error) *MockTokenStoreInterface_Consume_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTokenStoreInterface_Consume_Call) RunAndReturn(run func(ctx context.Context, purpose string, id string) (int64, error)) *MockTokenStoreInterface_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockTokenStoreInterface
func (_mock *MockTokenStoreInterface) Create(ctx context.Context, purpose string, userID int64, ttl time.Duration) (string, error) {
	ret := _mock.Called(ctx, purpose, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, time.Duration) (string, error)); ok {
		return returnFunc(ctx, purpose, userID, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, time.Duration) string); ok {
		r0 = returnFunc(ctx, purpose, userID, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, time.Duration) error); ok {
		r1 = returnFunc(ctx, purpose, userID, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenStoreInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTokenStoreInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - purpose string
//   - userID int64
//   - ttl time.Duration
func (_e *MockTokenStoreInterface_Expecter) Create(ctx interface{}, purpose interface{}, userID interface{}, ttl interface{}) *MockTokenStoreInterface_Create_Call {
	return &MockTokenStoreInterface_Create_Call{Call: _e.mock.On("Create", ctx, purpose, userID, ttl)}
}

func (_c *MockTokenStoreInterface_Create_Call) Run(run func(ctx context.Context, purpose string, userID int64, ttl time.Duration)) *MockTokenStoreInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTokenStoreInterface_Create_Call) Return(s string, err error) *MockTokenStoreInterface_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenStoreInterface_Create_Call) RunAndReturn(run func(ctx context.Context, purpose string, userID int64, ttl time.Duration) (string, error)) *MockTokenStoreInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}
