// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMailerInterface creates a new instance of MockMailerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailerInterface {
	mock := &MockMailerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMailerInterface is an autogenerated mock type for the MailerInterface type
type MockMailerInterface struct {
	mock.Mock
}

type MockMailerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailerInterface) EXPECT() *MockMailerInterface_Expecter {
	return &MockMailerInterface_Expecter{mock: &_m.Mock}
}

// SendConfirmationEmail provides a mock function for the type MockMailerInterface
func (_mock *MockMailerInterface) SendConfirmationEmail(to string, name string, link string) error {
	ret := _mock.Called(to, name, link)

	if len(ret) == 0 {
		panic("no return value specified for SendConfirmationEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(to, name, link)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMailerInterface_SendConfirmationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendConfirmationEmail'
type MockMailerInterface_SendConfirmationEmail_Call struct {
	*mock.Call
}

// SendConfirmationEmail is a helper method to define mock.On call
//   - to string
//   - name string
//   - link string
func (_e *MockMailerInterface_Expecter) SendConfirmationEmail(to interface{}, name interface{}, link interface{}) *MockMailerInterface_SendConfirmationEmail_Call {
	return &MockMailerInterface_SendConfirmationEmail_Call{Call: _e.mock.On("SendConfirmationEmail", to, name, link)}
}

func (_c *MockMailerInterface_SendConfirmationEmail_Call) Run(run func(to string, name string, link string)) *MockMailerInterface_SendConfirmationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMailerInterface_SendConfirmationEmail_Call) Return(err error) *MockMailerInterface_SendConfirmationEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMailerInterface_SendConfirmationEmail_Call) RunAndReturn(run func(to string, name string, link string) error) *MockMailerInterface_SendConfirmationEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendPasswordResetEmail provides a mock function for the type MockMailerInterface
func (_mock *MockMailerInterface) SendPasswordResetEmail(to string, name string, link string) error {
	ret := _mock.Called(to, name, link)

	if len(ret) == 0 {
		panic("no return value specified for SendPasswordResetEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(to, name, link)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMailerInterface_SendPasswordResetEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPasswordResetEmail'
type MockMailerInterface_SendPasswordResetEmail_Call struct {
	*mock.Call
}

// SendPasswordResetEmail is a helper method to define mock.On call
//   - to string
//   - name string
//   - link string
func (_e *MockMailerInterface_Expecter) SendPasswordResetEmail(to interface{}, name interface{}, link interface{}) *MockMailerInterface_SendPasswordResetEmail_Call {
	return &MockMailerInterface_SendPasswordResetEmail_Call{Call: _e.mock.On("SendPasswordResetEmail", to, name, link)}
}

func (_c *MockMailerInterface_SendPasswordResetEmail_Call) Run(run func(to string, name string, link string)) *MockMailerInterface_SendPasswordResetEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMailerInterface_SendPasswordResetEmail_Call) Return(err error) *MockMailerInterface_SendPasswordResetEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMailerInterface_SendPasswordResetEmail_Call) RunAndReturn(run func(to string, name string, link string) error) *MockMailerInterface_SendPasswordResetEmail_Call {
	_c.Call.Return(run)
	return _c
}
