// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "go-web-template/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockUserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type MockUserServiceInterface struct {
	mock.Mock
}

type MockUserServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceInterface) EXPECT() *MockUserServiceInterface_Expecter {
	return &MockUserServiceInterface_Expecter{mock: &_m.Mock}
}

// ListUsers provides a mock function with given fields: ctx, page, pageSize
func (_m *MockUserServiceInterface) ListUsers(ctx context.Context, page int, pageSize int) (*models.PaginatedUsers, error) {
	ret := _m.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *models.PaginatedUsers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*models.PaginatedUsers, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *models.PaginatedUsers); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaginatedUsers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceInterface_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserServiceInterface_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
func (_e *MockUserServiceInterface_Expecter) ListUsers(ctx interface{}, page interface{}, pageSize interface{}) *MockUserServiceInterface_ListUsers_Call {
	return &MockUserServiceInterface_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, page, pageSize)}
}

func (_c *MockUserServiceInterface_ListUsers_Call) Run(run func(ctx context.Context, page int, pageSize int)) *MockUserServiceInterface_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockUserServiceInterface_ListUsers_Call) Return(_a0 *models.PaginatedUsers, _a1 error) *MockUserServiceInterface_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceInterface_ListUsers_Call) RunAndReturn(run func(context.Context, int, int) (*models.PaginatedUsers, error)) *MockUserServiceInterface_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserServiceInterface creates a new instance of MockUserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
